version: '3.8'

services:
  db_back:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:latest
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
